# Generated by Django 4.0.5 on 2022-06-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время добавления')),
                ('longitude', models.CharField(blank=True, max_length=16, null=True, verbose_name='Долгота')),
                ('latitude', models.CharField(blank=True, max_length=16, null=True, verbose_name='Широта')),
                ('com', models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий к точке')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
    ]
