# Generated by Django 4.0.5 on 2022-06-18 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='com',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='location',
            name='dt',
        ),
        migrations.AddField(
            model_name='location',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 16, 59, 10, 462313), verbose_name='Дата и время добавления'),
            preserve_default=False,
        ),
    ]
