# Generated by Django 4.0.5 on 2022-06-19 14:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_com_location_comment_remove_location_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
